version: '3.8'

services:
  app:
    build:
      context:  C:\golang\petProjectV2
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - jwtSecret=arkadiy-boss
      - dbPass=123

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: